### ISSUE TITLE
OSError: libnvinfer.so.5 on jetson nano

### ISSUE THREAD

**Issue by SaddamBInSyed** [AastaNV/TRT_object_detection#17]
@AastaNV ,

while running the "python3 main.py object_7.jpg "
I am facing the below error, 

/home/deeplearning/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/deeplearning/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/deeplearning/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/deeplearning/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/deeplearning/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/deeplearning/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    ctypes.CDLL("/home/deeplearning/Downloads/TRT_object_detection/lib/libflattenconcat.so")
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libnvinfer.so.5: cannot open shared object file: No such file or directory

please advise

**Comment by Adnaram** [comment]
Same error here, please update.

**Comment by sdario1980** [comment]
Same error here

**Comment by Adnaram** [comment]
I found the solution. The libflattenconcat must be recompiled.

```
cd /usr/src/tensorrt/samples/python/uff_ssd/
mkdir build
cd build
cmake -D CMAKE_INSTALL_PREFIX=/usr/local ..
cp libflattenconcat.so /home/myuser/mycode

```

**Comment by sdario1980** [comment]
Thank you. However (it might be a stupid question, but in a linux beginner) where is the libflattenconcat.so generated? i can't find it.

Thanks

**Comment by Adnaram** [comment]
It should be in /usr/src/tensorrt/samples/python/uff_ssd/build if you run the commands above

**Comment by lakshaychhabra** [comment]
@Adnaram 

> I found the solution. The libflattenconcat must be recompiled.
> 
> ```
> cd /usr/src/tensorrt/samples/python/uff_ssd/
> mkdir build
> cd build
> cmake -D CMAKE_INSTALL_PREFIX=/usr/local ..
> cp libflattenconcat.so /home/myuser/mycode
> ```

remember to do 
>make
after cmake as per https://forums.developer.nvidia.com/t/problems-with-ssd-mobilenet-v2-uff/74326/17

**Comment by JohanneMoMiMo** [comment]
When I follow the steps above I get an error:

CMake Error: The source directory "/usr/src/tensorrt/samples/python/uff_ssd" does not appear to contain CMakeLists.txt.

Am I missing something?

**Comment by ram-ch** [comment]
Need help. I have tried this on Jetson AGX

cd /usr/src/tensorrt/samples/python/uff_ssd/
mkdir build
cd build
cmake -D CMAKE_INSTALL_PREFIX=/usr/local ..

Facing this issue
CMake Error: The source directory "/usr/src/tensorrt/samples/python/uff_ssd" does not appear to contain CMakeLists.txt.
